Monday, November 18th, 2019, 1:32:41 PM [info]: main - Successfully connected to the database
Monday, November 18th, 2019, 1:40:12 PM [info]: main - Successfully connected to the database
2019-11-18T08:00:55.996Z [error]: main - uncaughtException: Invalid atomic update value for $set. Expected an object, received undefined
Error: Invalid atomic update value for $set. Expected an object, received undefined
    at castUpdate (D:\trucklagbe_analytics\node_modules\mongoose\lib\helpers\query\castUpdate.js:93:13)
    at model.Query._castUpdate (D:\trucklagbe_analytics\node_modules\mongoose\lib\query.js:4442:10)
    at castDoc (D:\trucklagbe_analytics\node_modules\mongoose\lib\query.js:4470:18)
    at model.Query._updateThunk (D:\trucklagbe_analytics\node_modules\mongoose\lib\query.js:3667:20)
    at model.Query.<anonymous> (D:\trucklagbe_analytics\node_modules\mongoose\lib\query.js:3751:23)
    at model.Query._wrappedThunk [as _updateMany] (D:\trucklagbe_analytics\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8)
    at process.nextTick (D:\trucklagbe_analytics\node_modules\kareem\index.js:369:33)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Monday, November 18th, 2019, 2:12:20 PM [info]: main - Successfully connected to the database
Monday, November 18th, 2019, 2:18:10 PM [info]: main - Successfully connected to the database
Monday, November 18th, 2019, 2:19:30 PM [info]: main - Successfully connected to the database
Monday, November 18th, 2019, 3:40:42 PM [info]: main - Successfully connected to the database
2019-11-18T09:40:45.347Z [error]: main - uncaughtException: registeredUser validation failed: SMSUser: Cast to Boolean failed for value "True" at path "SMSUser"
ValidationError: registeredUser validation failed: SMSUser: Cast to Boolean failed for value "True" at path "SMSUser"
    at new ValidationError (D:\trucklagbe_analytics\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2413:32)
    at model.$set (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:1194:12)
    at model._handleIndex (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:934:14)
    at model.$set (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:878:22)
    at model.Document (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:136:12)
    at model.Model (D:\trucklagbe_analytics\node_modules\mongoose\lib\model.js:97:12)
    at new model (D:\trucklagbe_analytics\node_modules\mongoose\lib\model.js:4425:15)
    at Array.<anonymous> (D:\trucklagbe_analytics\node_modules\mongoose\lib\model.js:3212:15)
    at _start (D:\trucklagbe_analytics\node_modules\mongoose\lib\helpers\parallelLimit.js:27:37)
    at parallelLimit (D:\trucklagbe_analytics\node_modules\mongoose\lib\helpers\parallelLimit.js:23:5)
    at Function.Model.$__insertMany (D:\trucklagbe_analytics\node_modules\mongoose\lib\model.js:3233:3)
    at process.nextTick (D:\trucklagbe_analytics\node_modules\kareem\index.js:369:33)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Monday, November 18th, 2019, 3:41:31 PM [info]: main - Successfully connected to the database
Monday, November 18th, 2019, 4:04:36 PM [info]: main - Successfully connected to the database
Monday, November 18th, 2019, 4:47:17 PM [info]: main - Successfully connected to the database
Monday, November 18th, 2019, 5:17:03 PM [info]: main - Successfully connected to the database
2019-11-18T12:41:05.418Z [error]: main - uncaughtException: Invalid schema configuration: `True` is not a valid type at path `timestamps`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `True` is not a valid type at path `timestamps`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\loginUserModel.js:3:32)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\loginUser.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Monday, November 18th, 2019, 6:47:35 PM [info]: main - Successfully connected to the database
2019-11-18T12:52:28.383Z [error]: main - uncaughtException: Invalid schema configuration: `UTC` is not a valid type at path `LoginTime`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `UTC` is not a valid type at path `LoginTime`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\loginUserModel.js:3:32)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\loginUser.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-11-18T13:01:04.955Z [error]: main - uncaughtException: req is not defined
ReferenceError: req is not defined
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\loginUserModel.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\loginUser.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
2019-11-18T13:03:54.313Z [error]: main - uncaughtException: Date(...).toUTCString is not a function
TypeError: Date(...).toUTCString is not a function
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\loginUserModel.js:7:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\loginUser.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
Tuesday, November 19th, 2019, 12:43:15 PM [info]: main - Successfully connected to the database
Tuesday, November 19th, 2019, 1:00:28 PM [info]: main - Successfully connected to the database
Tuesday, November 19th, 2019, 1:02:09 PM [info]: main - Successfully connected to the database
Tuesday, November 19th, 2019, 1:06:33 PM [info]: main - Successfully connected to the database
2019-11-19T07:18:40.697Z [error]: main - uncaughtException: Route.post() requires a callback function but got a [object Undefined]
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.(anonymous function) [as post] (D:\trucklagbe_analytics\node_modules\express\lib\router\route.js:202:15)
    at Function.app.(anonymous function) [as post] (D:\trucklagbe_analytics\node_modules\express\lib\application.js:482:19)
    at Object.analyticsRoute (D:\trucklagbe_analytics\app\routes\api\analytics\route.js:46:9)
    at Object.<anonymous> (D:\trucklagbe_analytics\server.js:49:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Tuesday, November 19th, 2019, 1:20:06 PM [info]: main - Successfully connected to the database
Tuesday, November 19th, 2019, 1:59:50 PM [info]: main - Successfully connected to the database
Tuesday, November 19th, 2019, 3:25:04 PM [info]: main - Successfully connected to the database
Tuesday, November 19th, 2019, 4:36:26 PM [info]: main - Successfully connected to the database
Tuesday, November 19th, 2019, 4:48:19 PM [info]: main - Successfully connected to the database
Tuesday, November 19th, 2019, 5:41:34 PM [info]: main - Successfully connected to the database
2019-11-19T11:50:56.400Z [error]: main - uncaughtException: Cannot find module '../../../../libs/db/mongoDBModel/selectedTruckTypeModel'
Error: Cannot find module '../../../../libs/db/mongoDBModel/selectedTruckTypeModel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\selectedTruckType.js:1:32)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\controllers\analytics\selectedTruckType.js:1:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
Tuesday, November 19th, 2019, 6:02:06 PM [info]: main - Successfully connected to the database
2019-11-19T12:13:43.310Z [error]: main - uncaughtException: Route.post() requires a callback function but got a [object Undefined]
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.(anonymous function) [as post] (D:\trucklagbe_analytics\node_modules\express\lib\router\route.js:202:15)
    at Function.app.(anonymous function) [as post] (D:\trucklagbe_analytics\node_modules\express\lib\application.js:482:19)
    at Object.analyticsRoute (D:\trucklagbe_analytics\app\routes\api\analytics\route.js:89:9)
    at Object.<anonymous> (D:\trucklagbe_analytics\server.js:49:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Tuesday, November 19th, 2019, 6:15:01 PM [info]: main - Successfully connected to the database
Wednesday, November 20th, 2019, 2:08:23 PM [info]: main - Successfully connected to the database
2019-11-20T08:58:03.657Z [error]: main - uncaughtException: Cannot find module '../../../../libs/db/mongoDBModel/cancelTripModel'
Error: Cannot find module '../../../../libs/db/mongoDBModel/cancelTripModel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\cancelTrip.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\controllers\analytics\cancelTrip.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2019-11-20T09:00:28.799Z [error]: main - uncaughtException: Cannot find module '../../../../libs/db/mongoDBModel/cancelTripModel'
Error: Cannot find module '../../../../libs/db/mongoDBModel/cancelTripModel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\cancelTrip.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\controllers\analytics\cancelTrip.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2019-11-20T09:01:43.326Z [error]: main - uncaughtException: createdTripPickTimeSelected is not defined
ReferenceError: createdTripPickTimeSelected is not defined
    at Object.analyticsRoute (D:\trucklagbe_analytics\app\routes\api\analytics\route.js:103:9)
    at Object.<anonymous> (D:\trucklagbe_analytics\server.js:49:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Wednesday, November 20th, 2019, 3:03:49 PM [info]: main - Successfully connected to the database
Wednesday, November 20th, 2019, 4:46:06 PM [info]: main - Successfully connected to the database
2019-11-20T10:48:56.962Z [error]: main - uncaughtException: Cannot use 'in' operator to search for 'createdAt' in 7
TypeError: Cannot use 'in' operator to search for 'createdAt' in 7
    at handleTimestampOption (D:\trucklagbe_analytics\node_modules\mongoose\lib\helpers\schema\handleTimestampOption.js:20:14)
    at Schema.setupTimestamp (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:1084:21)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:139:8)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\discountModel.js:3:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\discount.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2019-11-20T10:49:49.488Z [error]: main - uncaughtException: Invalid schema configuration: `1574246989476` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `1574246989476` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\discountModel.js:3:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\discount.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-11-20T10:51:08.461Z [error]: main - uncaughtException: Invalid schema configuration: `undefined` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `undefined` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\discountModel.js:3:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\discount.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-11-20T10:52:57.892Z [error]: main - uncaughtException: Invalid schema configuration: `undefined` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `undefined` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\discountModel.js:3:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\discount.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-11-20T11:16:13.168Z [error]: main - uncaughtException: Invalid schema configuration: `undefined` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `undefined` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\discountModel.js:3:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\discount.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Wednesday, November 20th, 2019, 5:16:25 PM [info]: main - Successfully connected to the database
Wednesday, November 20th, 2019, 5:19:28 PM [info]: main - Successfully connected to the database
2019-11-20T11:26:13.924Z [error]: main - uncaughtException: Invalid schema configuration: `undefined` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `undefined` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\discountModel.js:3:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\discount.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-11-20T11:27:12.358Z [error]: main - uncaughtException: Invalid schema configuration: `undefined` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `undefined` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\discountModel.js:5:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\discount.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-11-20T11:27:44.704Z [error]: main - uncaughtException: Invalid schema configuration: `Wed Nov 20 2019 17:27:44 GMT+0600 (Bangladesh Standard Time)` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `Wed Nov 20 2019 17:27:44 GMT+0600 (Bangladesh Standard Time)` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\discountModel.js:5:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\discount.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-11-20T11:28:30.093Z [error]: main - uncaughtException: Invalid schema configuration: `Wed Nov 20 2019 17:28:30 GMT+0600 (Bangladesh Standard Time)` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `Wed Nov 20 2019 17:28:30 GMT+0600 (Bangladesh Standard Time)` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\discountModel.js:5:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\discount.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-11-20T11:28:56.407Z [error]: main - uncaughtException: Invalid schema configuration: `1574249336395` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `1574249336395` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\discountModel.js:5:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\discount.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-11-20T11:29:29.555Z [error]: main - uncaughtException: Invalid schema configuration: `undefined` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `undefined` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\discountModel.js:3:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\discount.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-11-20T11:30:18.291Z [error]: main - uncaughtException: Invalid schema configuration: `Wed Nov 20 2019 17:30:18 GMT+0600 (Bangladesh Standard Time)` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `Wed Nov 20 2019 17:30:18 GMT+0600 (Bangladesh Standard Time)` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\discountModel.js:3:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\discount.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Wednesday, November 20th, 2019, 5:54:17 PM [info]: main - Successfully connected to the database
Wednesday, November 20th, 2019, 5:59:43 PM [info]: main - Successfully connected to the database
Wednesday, November 20th, 2019, 6:08:03 PM [info]: main - Successfully connected to the database
2019-11-20T12:12:40.751Z [error]: main - uncaughtException: Cannot find module '../../../../libs/db/mongoDBModel/homeNavigationCheckModel'
Error: Cannot find module '../../../../libs/db/mongoDBModel/homeNavigationCheckModel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\homeNavigationCheck.js:1:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\controllers\analytics\homeNavigationCheck.js:1:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2019-11-20T12:14:14.621Z [error]: main - uncaughtException: Cannot find module '../../../../libs/db/mongoDBModel/homeNavigationCheckModel'
Error: Cannot find module '../../../../libs/db/mongoDBModel/homeNavigationCheckModel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\homeNavigationCheck.js:1:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\controllers\analytics\homeNavigationCheck.js:1:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2019-11-20T12:14:32.363Z [error]: main - uncaughtException: Cannot find module '../../../../libs/db/mongoDBModel/homeNavigationCheckModel'
Error: Cannot find module '../../../../libs/db/mongoDBModel/homeNavigationCheckModel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\homeNavigationCheck.js:1:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\controllers\analytics\homeNavigationCheck.js:1:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
Wednesday, November 20th, 2019, 6:15:19 PM [info]: main - Successfully connected to the database
2019-11-20T12:21:03.624Z [error]: main - uncaughtException: Cannot find module '../../../../libs/db/mongoDBModel/userProfileCheckModel'
Error: Cannot find module '../../../../libs/db/mongoDBModel/userProfileCheckModel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\userProfileCheck.js:1:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\controllers\analytics\userProfileCheck.js:1:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
Wednesday, November 20th, 2019, 6:23:05 PM [info]: main - Successfully connected to the database
Wednesday, November 20th, 2019, 7:04:40 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 10:45:37 AM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 11:12:09 AM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 11:13:17 AM [info]: main - Successfully connected to the database
2019-11-21T05:26:38.986Z [error]: main - uncaughtException: Invalid schema configuration: `Now` is not a valid type at path `DiscountDate`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `Now` is not a valid type at path `DiscountDate`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\discountModel.js:3:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\discount.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Thursday, November 21st, 2019, 11:27:10 AM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 12:55:22 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 1:04:16 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 1:10:46 PM [info]: main - Successfully connected to the database
2019-11-21T07:16:22.056Z [error]: main - uncaughtException: usersLocationtSchema is not defined
ReferenceError: usersLocationtSchema is not defined
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\usersLocationModel.js:14:75)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\usersLocation.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
Thursday, November 21st, 2019, 1:16:45 PM [info]: main - Successfully connected to the database
2019-11-21T07:28:19.628Z [error]: main - uncaughtException: Cannot find module '../../../api/controllers/analytics/appPopUpModel'
Error: Cannot find module '../../../api/controllers/analytics/appPopUpModel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\routes\api\analytics\route.js:29:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\routes\route.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
Thursday, November 21st, 2019, 1:29:32 PM [info]: main - Successfully connected to the database
2019-11-21T07:35:47.152Z [error]: main - uncaughtException: userAddTruckSchema is not defined
ReferenceError: userAddTruckSchema is not defined
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\userAddTruckModel.js:14:73)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\userAddTruck.js:1:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
Thursday, November 21st, 2019, 1:36:55 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 1:41:27 PM [info]: main - Successfully connected to the database
2019-11-21T07:47:16.375Z [error]: main - uncaughtException: Cannot find module '../../../../libs/db/mongoDBModel/feedBackModel'
Error: Cannot find module '../../../../libs/db/mongoDBModel/feedBackModel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\feedBack.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\controllers\analytics\feedBack.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2019-11-21T07:57:57.210Z [error]: main - uncaughtException: Cannot find module '../../../../libs/db/mongoDBModel/feedBackModel'
Error: Cannot find module '../../../../libs/db/mongoDBModel/feedBackModel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\feedBack.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\controllers\analytics\feedBack.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
Thursday, November 21st, 2019, 1:59:41 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 2:06:12 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 2:12:03 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 3:25:49 PM [info]: main - Successfully connected to the database
2019-11-21T10:07:25.247Z [error]: main - uncaughtException: Cannot find module '../utility/dateformat'
Error: Cannot find module '../utility/dateformat'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\loginUserModel.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\loginUser.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
Thursday, November 21st, 2019, 4:07:58 PM [info]: main - Successfully connected to the database
2019-11-21T10:08:10.266Z [error]: main - uncaughtException: Cast to date failed for value "Thursday, November 21st, 2019, 4:07:56 PM" at path "createdOn"
CastError: Cast to date failed for value "Thursday, November 21st, 2019, 4:07:56 PM" at path "createdOn"
    at new CastError (D:\trucklagbe_analytics\node_modules\mongoose\lib\error\cast.js:29:11)
    at SchemaDate.cast (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema\date.js:314:11)
    at SchemaDate.SchemaType.applySetters (D:\trucklagbe_analytics\node_modules\mongoose\lib\schematype.js:969:12)
    at SchemaDate.SchemaType.getDefault (D:\trucklagbe_analytics\node_modules\mongoose\lib\schematype.js:916:25)
    at $__applyDefaults (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:375:22)
    at model.Document (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:123:5)
    at model.Model (D:\trucklagbe_analytics\node_modules\mongoose\lib\model.js:97:12)
    at new model (D:\trucklagbe_analytics\node_modules\mongoose\lib\model.js:4425:15)
    at Array.<anonymous> (D:\trucklagbe_analytics\node_modules\mongoose\lib\model.js:3212:15)
    at _start (D:\trucklagbe_analytics\node_modules\mongoose\lib\helpers\parallelLimit.js:27:37)
    at parallelLimit (D:\trucklagbe_analytics\node_modules\mongoose\lib\helpers\parallelLimit.js:23:5)
    at Function.Model.$__insertMany (D:\trucklagbe_analytics\node_modules\mongoose\lib\model.js:3233:3)
    at process.nextTick (D:\trucklagbe_analytics\node_modules\kareem\index.js:369:33)
    at process._tickCallback (internal/process/next_tick.js:61:11)
2019-11-21T10:09:23.901Z [error]: main - uncaughtException: timestamp is not defined
ReferenceError: timestamp is not defined
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\loginUserModel.js:21:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\loginUser.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
2019-11-21T10:09:35.732Z [error]: main - uncaughtException: Invalid schema configuration: `11/21/2019, 4:09:35 PM` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `11/21/2019, 4:09:35 PM` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\loginUserModel.js:8:32)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\loginUser.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Thursday, November 21st, 2019, 4:09:48 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 4:14:29 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 4:16:43 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 4:19:03 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 4:21:44 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 4:22:44 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 4:24:40 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 4:27:26 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 4:30:34 PM [info]: main - Successfully connected to the database
Thursday, November 21st, 2019, 7:08:18 PM [info]: main - Successfully connected to the database
Saturday, November 23rd, 2019, 1:09:01 PM [info]: main - Successfully connected to the database
Saturday, November 23rd, 2019, 2:58:04 PM [info]: main - Successfully connected to the database
2019-11-23T08:58:41.181Z [error]: main - uncaughtException: discount validation failed: DiscountDate: Path `DiscountDate` is required.
ValidationError: discount validation failed: DiscountDate: Path `DiscountDate` is required.
    at new ValidationError (D:\trucklagbe_analytics\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2413:32)
    at p.doValidate.skipSchemaValidators (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2262:17)
    at D:\trucklagbe_analytics\node_modules\mongoose\lib\schematype.js:1058:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
Saturday, November 23rd, 2019, 2:59:23 PM [info]: main - Successfully connected to the database
2019-11-23T08:59:26.534Z [error]: main - uncaughtException: mapPinLocation validation failed: DropLocationAddress: Path `DropLocationAddress` is required., PickLocationAddress: Path `PickLocationAddress` is required.
ValidationError: mapPinLocation validation failed: DropLocationAddress: Path `DropLocationAddress` is required., PickLocationAddress: Path `PickLocationAddress` is required.
    at new ValidationError (D:\trucklagbe_analytics\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2413:32)
    at p.doValidate.skipSchemaValidators (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2262:17)
    at D:\trucklagbe_analytics\node_modules\mongoose\lib\schematype.js:1058:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
Saturday, November 23rd, 2019, 3:02:39 PM [info]: main - Successfully connected to the database
Saturday, November 23rd, 2019, 3:21:36 PM [info]: main - Successfully connected to the database
2019-11-23T09:21:43.149Z [error]: main - uncaughtException: loginUser validation failed: LoginTime: Path `LoginTime` is required., UserName: Path `UserName` is required.
ValidationError: loginUser validation failed: LoginTime: Path `LoginTime` is required., UserName: Path `UserName` is required.
    at new ValidationError (D:\trucklagbe_analytics\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2413:32)
    at p.doValidate.skipSchemaValidators (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2262:17)
    at D:\trucklagbe_analytics\node_modules\mongoose\lib\schematype.js:1058:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
Saturday, November 23rd, 2019, 3:26:55 PM [info]: main - Successfully connected to the database
2019-11-23T09:27:00.343Z [error]: main - uncaughtException: loginUser validation failed: LoginTime: Path `LoginTime` is required., UserName: Path `UserName` is required.
ValidationError: loginUser validation failed: LoginTime: Path `LoginTime` is required., UserName: Path `UserName` is required.
    at new ValidationError (D:\trucklagbe_analytics\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2413:32)
    at p.doValidate.skipSchemaValidators (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2262:17)
    at D:\trucklagbe_analytics\node_modules\mongoose\lib\schematype.js:1058:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
Saturday, November 23rd, 2019, 3:27:28 PM [info]: main - Successfully connected to the database
Saturday, November 23rd, 2019, 3:29:18 PM [info]: main - Successfully connected to the database
Saturday, November 23rd, 2019, 3:29:53 PM [info]: main - Successfully connected to the database
Saturday, November 23rd, 2019, 3:30:51 PM [info]: main - Successfully connected to the database
2019-11-23T09:30:52.651Z [error]: main - uncaughtException: loginUser validation failed: UserName: Path `UserName` is required.
ValidationError: loginUser validation failed: UserName: Path `UserName` is required.
    at new ValidationError (D:\trucklagbe_analytics\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2413:32)
    at p.doValidate.skipSchemaValidators (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2262:17)
    at D:\trucklagbe_analytics\node_modules\mongoose\lib\schematype.js:1058:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
Saturday, November 23rd, 2019, 3:32:07 PM [info]: main - Successfully connected to the database
Saturday, November 23rd, 2019, 3:32:47 PM [info]: main - Successfully connected to the database
Saturday, November 23rd, 2019, 3:34:44 PM [info]: main - Successfully connected to the database
Saturday, November 23rd, 2019, 4:19:58 PM [info]: main - Successfully connected to the database
Wednesday, November 27th, 2019, 3:04:29 PM [info]: main - Successfully connected to the database
Wednesday, November 27th, 2019, 3:05:44 PM [info]: main - Successfully connected to the database
Wednesday, November 27th, 2019, 3:06:15 PM [info]: main - Successfully connected to the database
Wednesday, November 27th, 2019, 3:16:26 PM [info]: main - Successfully connected to the database
Wednesday, November 27th, 2019, 3:22:21 PM [info]: main - Successfully connected to the database
Wednesday, November 27th, 2019, 3:31:31 PM [info]: main - Successfully connected to the database
Wednesday, November 27th, 2019, 3:34:05 PM [info]: main - Successfully connected to the database
Wednesday, November 27th, 2019, 4:41:29 PM [info]: main - Successfully connected to the database
Wednesday, November 27th, 2019, 4:41:55 PM [info]: main - Successfully connected to the database
Thursday, November 28th, 2019, 12:24:58 PM [info]: main - Successfully connected to the database
Thursday, November 28th, 2019, 12:25:49 PM [info]: main - Successfully connected to the database
Thursday, November 28th, 2019, 12:30:03 PM [info]: main - Successfully connected to the database
Thursday, November 28th, 2019, 5:06:40 PM [info]: main - Successfully connected to the database
2019-12-01T06:23:41.804Z [error]: main - uncaughtException: Invalid schema configuration: `2019-12-01 12:23:41` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
TypeError: Invalid schema configuration: `2019-12-01 12:23:41` is not a valid type at path `createdOn`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:905:11)
    at Schema.path (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:606:27)
    at Schema.add (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:446:12)
    at new Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:123:10)
    at Mongoose.Schema (D:\trucklagbe_analytics\node_modules\mongoose\lib\schema.js:88:12)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\appCrashReportModel.js:14:37)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\appCrashReport.js:1:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Monday, December 2nd, 2019, 6:36:37 PM [info]: main - Successfully connected to the database
Monday, December 2nd, 2019, 8:36:25 PM [info]: main - Successfully connected to the database
Monday, December 2nd, 2019, 8:42:54 PM [info]: main - Successfully connected to the database
Monday, December 2nd, 2019, 8:47:51 PM [info]: main - Successfully connected to the database
Monday, December 2nd, 2019, 9:02:06 PM [info]: main - Successfully connected to the database
Tuesday, December 3rd, 2019, 10:28:34 AM [info]: main - Successfully connected to the database
Tuesday, December 3rd, 2019, 10:36:57 AM [info]: main - Successfully connected to the database
Tuesday, December 3rd, 2019, 10:53:06 AM [info]: main - Successfully connected to the database
Tuesday, December 3rd, 2019, 12:05:23 PM [info]: main - Successfully connected to the database
2019-12-04T05:30:21.249Z [error]: main - uncaughtException: res is not defined
ReferenceError: res is not defined
    at Object.analyticsRoute (D:\trucklagbe_analytics\app\routes\api\analytics\route.js:60:9)
    at Object.<anonymous> (D:\trucklagbe_analytics\server.js:49:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Wednesday, December 4th, 2019, 11:31:22 AM [info]: main - Successfully connected to the database
Thursday, December 19th, 2019, 7:05:34 PM [info]: main - Successfully connected to the database
Thursday, December 19th, 2019, 8:00:50 PM [info]: main - Successfully connected to the database
Monday, December 23rd, 2019, 4:26:26 PM [info]: main - Successfully connected to the database
Monday, December 23rd, 2019, 4:28:31 PM [info]: main - Successfully connected to the database
2019-12-23T10:30:18.989Z [error]: main - uncaughtException: appCrashReport validation failed: reason: Path `reason` is required.
ValidationError: appCrashReport validation failed: reason: Path `reason` is required.
    at new ValidationError (D:\trucklagbe_analytics\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2413:32)
    at p.doValidate.skipSchemaValidators (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2262:17)
    at D:\trucklagbe_analytics\node_modules\mongoose\lib\schematype.js:1058:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
Monday, December 23rd, 2019, 4:30:50 PM [info]: main - Successfully connected to the database
2019-12-23T10:30:58.030Z [error]: main - uncaughtException: appCrashReport validation failed: reason: Path `reason` is required.
ValidationError: appCrashReport validation failed: reason: Path `reason` is required.
    at new ValidationError (D:\trucklagbe_analytics\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2413:32)
    at p.doValidate.skipSchemaValidators (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2262:17)
    at D:\trucklagbe_analytics\node_modules\mongoose\lib\schematype.js:1058:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
Monday, December 23rd, 2019, 4:35:14 PM [info]: main - Successfully connected to the database
2019-12-23T10:35:16.200Z [error]: main - uncaughtException: appCrashReport validation failed: reason: Path `reason` is required.
ValidationError: appCrashReport validation failed: reason: Path `reason` is required.
    at new ValidationError (D:\trucklagbe_analytics\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2413:32)
    at p.doValidate.skipSchemaValidators (D:\trucklagbe_analytics\node_modules\mongoose\lib\document.js:2262:17)
    at D:\trucklagbe_analytics\node_modules\mongoose\lib\schematype.js:1058:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
Monday, December 23rd, 2019, 4:36:03 PM [info]: main - Successfully connected to the database
Monday, December 23rd, 2019, 4:41:26 PM [info]: main - Successfully connected to the database
Monday, December 23rd, 2019, 5:22:02 PM [info]: main - Successfully connected to the database
Wednesday, January 1st, 2020, 1:58:52 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 12:52:05 PM [info]: main - Successfully connected to the database
2020-01-07T08:06:48.021Z [error]: main - uncaughtException: Cannot read property 'toLocaleString' of undefined
TypeError: Cannot read property 'toLocaleString' of undefined
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:4:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\savedLocation.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
Tuesday, January 7th, 2020, 2:07:05 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 2:08:19 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 2:08:43 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 2:10:50 PM [info]: main - Successfully connected to the database
2020-01-07T08:16:09.091Z [error]: main - uncaughtException: Cannot read property 'now' of undefined
TypeError: Cannot read property 'now' of undefined
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\savedLocation.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
2020-01-07T08:16:26.389Z [error]: main - uncaughtException: Cannot read property 'now' of undefined
TypeError: Cannot read property 'now' of undefined
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\savedLocation.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
Tuesday, January 7th, 2020, 2:21:49 PM [info]: main - Successfully connected to the database
2020-01-07T08:23:23.838Z [error]: main - uncaughtException: Date.now is not a constructor
TypeError: Date.now is not a constructor
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\savedLocation.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
2020-01-07T08:23:40.469Z [error]: main - uncaughtException: Invalid date
TypeError: Invalid date
    at D:\trucklagbe_analytics\libs\utility\dateformat.js:26:19
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:6:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\savedLocation.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-01-07T08:24:38.977Z [error]: main - uncaughtException: Invalid date
TypeError: Invalid date
    at D:\trucklagbe_analytics\libs\utility\dateformat.js:26:19
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:7:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\savedLocation.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-01-07T08:25:12.744Z [error]: main - uncaughtException: Invalid date
TypeError: Invalid date
    at D:\trucklagbe_analytics\libs\utility\dateformat.js:26:19
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:6:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\savedLocation.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-01-07T08:25:27.137Z [error]: main - uncaughtException: Invalid date
TypeError: Invalid date
    at D:\trucklagbe_analytics\libs\utility\dateformat.js:26:19
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:6:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\savedLocation.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
Tuesday, January 7th, 2020, 2:29:18 PM [info]: main - Successfully connected to the database
2020-01-07T08:30:34.094Z [error]: main - uncaughtException: Invalid time value
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at NOW (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:6:45)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:30:40)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\savedLocation.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2020-01-07T08:30:47.672Z [error]: main - uncaughtException: Date.now is not a constructor
TypeError: Date.now is not a constructor
    at NOW (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:6:21)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:30:40)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\savedLocation.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-01-07T08:31:12.275Z [error]: main - uncaughtException: Invalid time value
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at NOW (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:6:45)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:30:40)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\savedLocation.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Tuesday, January 7th, 2020, 2:32:55 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 2:34:01 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 2:35:29 PM [info]: main - Successfully connected to the database
2020-01-07T08:36:27.576Z [error]: main - uncaughtException: dateFormat is not defined
ReferenceError: dateFormat is not defined
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\savedLocation.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
2020-01-07T08:36:41.037Z [error]: main - uncaughtException: Invalid date
TypeError: Invalid date
    at D:\trucklagbe_analytics\libs\utility\dateformat.js:26:19
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:9:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\savedLocation.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
Tuesday, January 7th, 2020, 2:37:30 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 2:39:17 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 2:40:56 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 2:41:55 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 2:47:54 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 2:49:40 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 2:50:48 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 2:52:00 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 2:52:53 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 6:19:32 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 6:19:54 PM [info]: main - Successfully connected to the database
2020-01-07T12:25:54.257Z [error]: main - uncaughtException: Invalid date
TypeError: Invalid date
    at D:\trucklagbe_analytics\libs\utility\dateformat.js:26:19
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\savedLocationModel.js:10:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\savedLocation.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
Tuesday, January 7th, 2020, 6:27:37 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 6:29:07 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 6:37:31 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 6:39:34 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 7:00:35 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 7:01:47 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 7:41:55 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 7:42:09 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 7:56:46 PM [info]: main - Successfully connected to the database
2020-01-07T13:57:19.054Z [error]: main - uncaughtException: logger is not defined
ReferenceError: logger is not defined
    at Request._callback (D:\trucklagbe_analytics\common\middleware\authValidation.js:91:17)
    at self.callback (D:\trucklagbe_analytics\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (D:\trucklagbe_analytics\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Tuesday, January 7th, 2020, 7:59:32 PM [info]: main - Successfully connected to the database
Tuesday, January 7th, 2020, 8:14:29 PM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 11:16:20 AM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 11:35:00 AM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 11:37:10 AM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 11:39:05 AM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 11:39:48 AM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 11:43:20 AM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 11:44:03 AM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 11:50:33 AM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 12:00:10 PM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 12:01:51 PM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 12:04:57 PM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 12:07:06 PM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 12:08:44 PM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 1:51:37 PM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 1:53:36 PM [info]: main - Successfully connected to the database
2020-01-09T07:53:37.242Z [error]: main - uncaughtException: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (D:\trucklagbe_analytics\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (D:\trucklagbe_analytics\node_modules\express\lib\response.js:170:12)
    at D:\trucklagbe_analytics\app\api\controllers\analytics\selectedTruckType.js:29:33
    at D:\trucklagbe_analytics\app\api\model\analytics\selectedTruckType.js:14:9
    at D:\trucklagbe_analytics\node_modules\mongoose\lib\utils.js:276:16
    at D:\trucklagbe_analytics\node_modules\mongoose\lib\model.js:4604:16
    at D:\trucklagbe_analytics\node_modules\mongoose\lib\model.js:3276:7
    at result (D:\trucklagbe_analytics\node_modules\mongodb\lib\operations\execute_operation.js:75:17)
    at session.endSession (D:\trucklagbe_analytics\node_modules\mongodb\lib\operations\execute_operation.js:64:11)
    at ClientSession.endSession (D:\trucklagbe_analytics\node_modules\mongodb\lib\core\sessions.js:135:41)
    at executeCallback (D:\trucklagbe_analytics\node_modules\mongodb\lib\operations\execute_operation.js:59:17)
    at bulkWriteOperation.execute (D:\trucklagbe_analytics\node_modules\mongodb\lib\operations\insert_many.js:43:7)
    at bulk.execute (D:\trucklagbe_analytics\node_modules\mongodb\lib\operations\bulk_write.js:99:7)
    at result (D:\trucklagbe_analytics\node_modules\mongodb\lib\utils.js:411:17)
    at executeCallback (D:\trucklagbe_analytics\node_modules\mongodb\lib\utils.js:403:9)
Thursday, January 9th, 2020, 1:56:59 PM [info]: main - Successfully connected to the database
2020-01-09T07:57:01.845Z [error]: main - uncaughtException: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (D:\trucklagbe_analytics\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (D:\trucklagbe_analytics\node_modules\express\lib\response.js:170:12)
    at D:\trucklagbe_analytics\app\api\controllers\analytics\selectedTruckType.js:44:33
    at D:\trucklagbe_analytics\app\api\model\analytics\selectedTruckType.js:14:9
    at D:\trucklagbe_analytics\node_modules\mongoose\lib\utils.js:276:16
    at D:\trucklagbe_analytics\node_modules\mongoose\lib\model.js:4604:16
    at D:\trucklagbe_analytics\node_modules\mongoose\lib\model.js:3276:7
    at result (D:\trucklagbe_analytics\node_modules\mongodb\lib\operations\execute_operation.js:75:17)
    at session.endSession (D:\trucklagbe_analytics\node_modules\mongodb\lib\operations\execute_operation.js:64:11)
    at ClientSession.endSession (D:\trucklagbe_analytics\node_modules\mongodb\lib\core\sessions.js:135:41)
    at executeCallback (D:\trucklagbe_analytics\node_modules\mongodb\lib\operations\execute_operation.js:59:17)
    at bulkWriteOperation.execute (D:\trucklagbe_analytics\node_modules\mongodb\lib\operations\insert_many.js:43:7)
    at bulk.execute (D:\trucklagbe_analytics\node_modules\mongodb\lib\operations\bulk_write.js:99:7)
    at result (D:\trucklagbe_analytics\node_modules\mongodb\lib\utils.js:411:17)
    at executeCallback (D:\trucklagbe_analytics\node_modules\mongodb\lib\utils.js:403:9)
Thursday, January 9th, 2020, 1:58:02 PM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 2:01:10 PM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 2:05:42 PM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 2:07:38 PM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 2:12:01 PM [info]: main - Successfully connected to the database
Thursday, January 9th, 2020, 2:22:54 PM [info]: main - Successfully connected to the database
Thursday, January 16th, 2020, 3:37:02 PM [info]: main - Successfully connected to the database
Thursday, January 16th, 2020, 3:41:05 PM [info]: main - Successfully connected to the database
Thursday, January 16th, 2020, 5:11:33 PM [info]: main - Successfully connected to the database
Monday, February 3rd, 2020, 10:46:53 AM [info]: main - Successfully connected to the database
Monday, February 3rd, 2020, 10:47:52 AM [info]: main - Successfully connected to the database
Monday, February 3rd, 2020, 10:49:38 AM [info]: main - Successfully connected to the database
Monday, February 3rd, 2020, 10:50:06 AM [info]: main - Successfully connected to the database
Monday, February 3rd, 2020, 11:02:01 AM [info]: main - Successfully connected to the database
2020-02-03T05:14:43.655Z [error]: main - uncaughtException: Route.post() requires a callback function but got a [object Undefined]
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.(anonymous function) [as post] (D:\trucklagbe_analytics\node_modules\express\lib\router\route.js:202:15)
    at Function.app.(anonymous function) [as post] (D:\trucklagbe_analytics\node_modules\express\lib\application.js:482:19)
    at Object.analyticsRoute (D:\trucklagbe_analytics\app\routes\api\analytics\route.js:243:9)
    at Object.<anonymous> (D:\trucklagbe_analytics\server.js:49:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Monday, February 3rd, 2020, 11:15:24 AM [info]: main - Successfully connected to the database
Monday, February 3rd, 2020, 11:16:46 AM [info]: main - Successfully connected to the database
Monday, February 3rd, 2020, 11:17:23 AM [info]: main - Successfully connected to the database
Monday, February 3rd, 2020, 11:18:50 AM [info]: main - Successfully connected to the database
Monday, February 3rd, 2020, 11:29:41 AM [info]: main - Successfully connected to the database
Monday, February 3rd, 2020, 11:31:34 AM [info]: main - Successfully connected to the database
2020-02-19T06:40:23.120Z [error]: main - uncaughtException: Cannot overwrite `loginUser` model once compiled.
OverwriteModelError: Cannot overwrite `loginUser` model once compiled.
    at new OverwriteModelError (D:\trucklagbe_analytics\node_modules\mongoose\lib\error\overwriteModel.js:20:11)
    at Mongoose.model (D:\trucklagbe_analytics\node_modules\mongoose\lib\index.js:517:13)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\homePageLaunchModel.js:25:53)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\homePageLaunch.js:1:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Wednesday, February 19th, 2020, 12:41:32 PM [info]: main - Successfully connected to the database
Wednesday, February 19th, 2020, 1:21:02 PM [info]: main - Successfully connected to the database
2020-02-19T07:41:58.883Z [error]: main - uncaughtException: Cannot overwrite `ownerTripShow` model once compiled.
OverwriteModelError: Cannot overwrite `ownerTripShow` model once compiled.
    at new OverwriteModelError (D:\trucklagbe_analytics\node_modules\mongoose\lib\error\overwriteModel.js:20:11)
    at Mongoose.model (D:\trucklagbe_analytics\node_modules\mongoose\lib\index.js:517:13)
    at Object.<anonymous> (D:\trucklagbe_analytics\libs\db\mongoDBModel\ownerTripDetailsShowModel.js:32:52)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\trucklagbe_analytics\app\api\model\analytics\ownerTripDetailsShow.js:1:35)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Wednesday, February 19th, 2020, 1:42:31 PM [info]: main - Successfully connected to the database
Wednesday, February 19th, 2020, 1:58:54 PM [info]: main - Successfully connected to the database
Monday, February 24th, 2020, 11:53:39 AM [info]: main - Successfully connected to the database
Sunday, June 14th, 2020, 11:44:03 AM [info]: main - Successfully connected to the database
Wednesday, June 24th, 2020, 12:42:18 PM [info]: main - Successfully connected to the database
